# Generated by Django 4.2.7 on 2024-02-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_state', models.CharField(max_length=255)),
                ('answer_points', models.IntegerField()),
                ('answer_points_statement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField()),
                ('question_answer', models.CharField(max_length=255)),
                ('question_difficulty', models.IntegerField()),
                ('question_timer', models.IntegerField()),
                ('question_marks', models.IntegerField()),
            ],
        ),
    ]
