# Generated by Django 4.2.7 on 2024-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenquestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allquestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField()),
                ('timer', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
