# Generated by Django 4.2.7 on 2024-02-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenquestions', '0002_allquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allquestions',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
