# Generated by Django 4.2.7 on 2024-03-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writtenquestions', '0003_alter_allquestions_timer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='user_question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_points_statement',
        ),
        migrations.AlterField(
            model_name='allquestions',
            name='timer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_state',
            field=models.BooleanField(),
        ),
    ]
